#!/bin/bash

set -exo pipefail

if [[ "${DISTRO_NAME}${DISTRO_VER}" == "centos7" ]]; then
  # Disable outdated repos; use vault instead
  sed -i '/^enabled=/d; /^\[/a\enabled=0' /etc/yum.repos.d/CentOS-Base.repo
  cp "/tmp/centos7-repos/centos7-$(uname -m)-vault.repo" /etc/yum.repos.d/vault.repo

  # Resolves a nasty NOKEY warning that appears when using yum.
  rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
  if [[ "$(uname -m)" == "ppc64le" ]]; then
    rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-AltArch-7-ppc64le
  elif [[ "$(uname -m)" == "aarch64" ]]; then
    rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7-aarch64
  fi
fi

rm -rf "/tmp/centos7-repos"
